// ─── TYPES ────────────────────────────────────────────────────────────────────
export interface Player {
  name: string;
  position: string;
  number: number;
}

export interface Team {
  slug: string;
  name: string;
  ageGroup: string;
  description: string;
  image: string;
  wins: number;
  draws: number;
  losses: number;
  played: number;
  pointsFor: number;
  pointsAgainst: number;
  training: string;
  ground: string;
  coach: string;
  sponsor: string;
  players: Player[];
}

// ─── TEAMS ────────────────────────────────────────────────────────────────────
export const teams: Team[] = [
  {
    slug: "senior-men",
    name: "County Senior Men",
    ageGroup: "Senior Men",
    description: "Our senior men's squad competing in the Southwest Ontario Rugby Union. A mix of experienced players and new talent representing Waterloo County in contact rugby.",
    image: "https://images.pexels.com/photos/8592966/pexels-photo-8592966.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "Visit the club for 2026 schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Contact club for details",
    sponsor: "Josslin Insurance",
    players: [],
  },
  {
    slug: "senior-women",
    name: "County Senior Women",
    ageGroup: "Senior Women",
    description: "Our women's senior team competing in SWORU contact rugby. Open to all women looking to play competitive rugby in the Waterloo Region.",
    image: "https://images.pexels.com/photos/6807428/pexels-photo-6807428.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "Visit the club for 2026 schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Contact club for details",
    sponsor: "",
    players: [],
  },
  {
    slug: "mixed-social",
    name: "Mixed Ability / Social",
    ageGroup: "Social",
    description: "Rugby for everyone — no experience needed. Our social and mixed-ability team is the perfect way to try the game in a welcoming, low-pressure environment.",
    image: "https://images.pexels.com/photos/33758975/pexels-photo-33758975.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "Visit the club for 2026 schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Contact club for details",
    sponsor: "",
    players: [],
  },
  {
    slug: "u18-men",
    name: "County U18 Men",
    ageGroup: "Under 18 Men",
    description: "Junior contact rugby for players born in 2008 or later. Competing in SWORU's U18 league with pathways to provincial selection through the Ontario Blues Development Academy.",
    image: "https://images.pexels.com/photos/35102702/pexels-photo-35102702.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 1, draws: 0, losses: 1, played: 2,
    pointsFor: 34, pointsAgainst: 34,
    training: "See 2026 season schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Trevor Williams (Director of Junior Rugby)",
    sponsor: "",
    players: [],
  },
  {
    slug: "u18-women",
    name: "County U18 Women",
    ageGroup: "Under 18 Women",
    description: "Junior contact rugby for female players born in 2008 or later. Building the next generation of women's rugby talent in Waterloo Region.",
    image: "https://images.pexels.com/photos/20399912/pexels-photo-20399912.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "See 2026 season schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Trevor Williams (Director of Junior Rugby)",
    sponsor: "",
    players: [],
  },
  {
    slug: "u16-boys",
    name: "County U16 Boys",
    ageGroup: "Under 16 Boys",
    description: "One of our most active teams — 2025 Rugby Ontario U16 Provincial Champions! Boys born in 2010 or later competing at the highest junior level in the province.",
    image: "https://images.pexels.com/photos/3641367/pexels-photo-3641367.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "See 2026 season schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Trevor Williams (Director of Junior Rugby)",
    sponsor: "",
    players: [],
  },
  {
    slug: "u16-girls",
    name: "County U16 Girls",
    ageGroup: "Under 16 Girls",
    description: "Contact rugby for girls born in 2010 or later. A fast-growing programme with pathways to SWORU provincial competition.",
    image: "https://images.pexels.com/photos/36305848/pexels-photo-36305848.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "See 2026 season schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Trevor Williams (Director of Junior Rugby)",
    sponsor: "",
    players: [],
  },
  {
    slug: "u14-boys",
    name: "County U14 Boys",
    ageGroup: "Under 14 Boys",
    description: "Contact rugby for boys born in 2012 or later. Combined programme with Guelph RFC to maximise competition and development opportunities.",
    image: "https://images.pexels.com/photos/9799211/pexels-photo-9799211.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "See 2026 season schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Trevor Williams (Director of Junior Rugby)",
    sponsor: "",
    players: [],
  },
  {
    slug: "u14-girls",
    name: "County U14 Girls",
    ageGroup: "Under 14 Girls",
    description: "Contact rugby for girls born in 2012 or later. Combined with Guelph RFC for richer competition.",
    image: "https://images.pexels.com/photos/20399907/pexels-photo-20399907.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "See 2026 season schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Trevor Williams (Director of Junior Rugby)",
    sponsor: "",
    players: [],
  },
  {
    slug: "u12-contact",
    name: "County U12 Contact",
    ageGroup: "Under 12 Contact",
    description: "Introduction to contact rugby for boys and girls born in 2014 or later. Safe, structured, and fun — the gateway to competitive rugby.",
    image: "https://images.pexels.com/photos/17341038/pexels-photo-17341038.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "See 2026 season schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Trevor Williams (Director of Junior Rugby)",
    sponsor: "",
    players: [],
  },
  {
    slug: "u10-flag",
    name: "County U10 Flag",
    ageGroup: "Under 10 Flag",
    description: "Non-contact flag rugby for players born in 2016 or later. All the fun of rugby — running, passing, and teamwork — without contact. Perfect for first-timers.",
    image: "https://images.unsplash.com/photo-1613332331877-8a47030be80b?w=800&q=80",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "See 2026 season schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Trevor Williams (Director of Junior Rugby)",
    sponsor: "",
    players: [],
  },
  {
    slug: "u8-flag",
    name: "County U8 Flag",
    ageGroup: "Under 8 Flag",
    description: "Fun, non-contact flag rugby for our youngest players born in 2018 or later. Gilbert Canada kit included. Come enjoy the game at its most joyful!",
    image: "https://images.pexels.com/photos/31003857/pexels-photo-31003857.jpeg?auto=compress&cs=tinysrgb&w=800",
    wins: 0, draws: 0, losses: 0, played: 0,
    pointsFor: 0, pointsAgainst: 0,
    training: "See 2026 season schedule",
    ground: "80 Bluevale Street North, Waterloo, ON",
    coach: "Trevor Williams (Director of Junior Rugby)",
    sponsor: "",
    players: [],
  },
];

// ─── FIXTURES & RESULTS ───────────────────────────────────────────────────────
// Real results from 2025 season (from photo albums and match records)
export const fixtures = [
  // 2026 Season — Upcoming (to be updated when schedule is published)
  {
    id: "f-2026-01",
    date: "2026-06-07T14:00:00",
    home: "Waterloo County RFC",
    away: "Burlington RFC",
    homeScore: null,
    awayScore: null,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "SWORU Senior Men",
    team: "senior-men",
    isHome: true,
  },
  {
    id: "f-2026-02",
    date: "2026-06-14T14:00:00",
    home: "Guelph RFC",
    away: "Waterloo County RFC",
    homeScore: null,
    awayScore: null,
    venue: "Alumni Stadium, Guelph",
    competition: "SWORU Senior Men",
    team: "senior-men",
    isHome: false,
  },
  {
    id: "f-2026-03",
    date: "2026-06-21T11:00:00",
    home: "Waterloo County U16 Boys",
    away: "Brantford RFC U16",
    homeScore: null,
    awayScore: null,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "SWORU U16 Boys League",
    team: "u16-boys",
    isHome: true,
  },
  {
    id: "f-2026-04",
    date: "2026-06-28T11:00:00",
    home: "Waterloo County U18 Men",
    away: "Fergus RFC U18",
    homeScore: null,
    awayScore: null,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "SWORU U18 Men's League",
    team: "u18-men",
    isHome: true,
  },
  // 2025 Season Results (from photo albums & match records)
  {
    id: "r-2025-u18-01",
    date: "2025-08-12T14:00:00",
    home: "Brantford RFC U18",
    away: "Waterloo County U18",
    homeScore: null,
    awayScore: null,
    venue: "Brantford",
    competition: "SWORU U18 League — Final Game",
    team: "u18-men",
    isHome: false,
  },
  {
    id: "r-2025-u18-02",
    date: "2025-08-03T14:00:00",
    home: "Waterloo County U18",
    away: "Sarnia RFC U18",
    homeScore: null,
    awayScore: null,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "SWORU U18 Playoff",
    team: "u18-men",
    isHome: true,
  },
  {
    id: "r-2025-u18-03",
    date: "2025-07-27T14:00:00",
    home: "Waterloo County U18",
    away: "Burlington RFC U18",
    homeScore: null,
    awayScore: null,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "SWORU U18 League",
    team: "u18-men",
    isHome: true,
  },
  {
    id: "r-2025-u18-04",
    date: "2025-06-29T14:00:00",
    home: "Sarnia RFC U18",
    away: "Waterloo County U18",
    homeScore: null,
    awayScore: null,
    venue: "Sarnia",
    competition: "SWORU U18 League",
    team: "u18-men",
    isHome: false,
  },
  // U18 results with known scores
  {
    id: "r-2025-u18-fergus",
    date: "2025-07-19T14:00:00",
    home: "Fergus RFC U18",
    away: "Waterloo County U18",
    homeScore: 29,
    awayScore: 5,
    venue: "Fergus",
    competition: "SWORU U18 League",
    team: "u18-men",
    isHome: false,
  },
  {
    id: "r-2025-u18-london",
    date: "2025-07-12T14:00:00",
    home: "Waterloo County U18",
    away: "London RFC U18",
    homeScore: 29,
    awayScore: 24,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "SWORU U18 League",
    team: "u18-men",
    isHome: true,
  },
  // U16 Championship Season 2025
  {
    id: "r-2025-u16-champ",
    date: "2025-07-26T14:00:00",
    home: "Waterloo County U16 Boys",
    away: "Guelph RFC U16",
    homeScore: null,
    awayScore: null,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "Rugby Ontario U16 Provincial Championship",
    team: "u16-boys",
    isHome: true,
  },
  {
    id: "r-2025-u16-peterborough",
    date: "2025-08-10T11:00:00",
    home: "Waterloo County U16 Boys",
    away: "Peterborough / Barrhaven",
    homeScore: null,
    awayScore: null,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "SWORU U16 Boys League",
    team: "u16-boys",
    isHome: true,
  },
  {
    id: "r-2025-u16-middlesex",
    date: "2025-07-26T11:00:00",
    home: "Waterloo County U16 Boys",
    away: "Middlesex / Sarnia U16",
    homeScore: null,
    awayScore: null,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "SWORU U16 Boys League",
    team: "u16-boys",
    isHome: true,
  },
  {
    id: "r-2025-u16-brantford-jul19",
    date: "2025-07-19T11:00:00",
    home: "Waterloo County U16 Boys",
    away: "Brantford RFC U16",
    homeScore: null,
    awayScore: null,
    venue: "80 Bluevale Street North, Waterloo",
    competition: "SWORU U16 Boys League",
    team: "u16-boys",
    isHome: true,
  },
];

// ─── LEAGUE STANDINGS ─────────────────────────────────────────────────────────
// 2026 season standings — to be updated as season progresses
export const standings = [
  { pos: 1, team: "Waterloo County RFC", p: 0, w: 0, d: 0, l: 0, pf: 0, pa: 0, pts: 0 },
  { pos: 2, team: "Guelph RFC", p: 0, w: 0, d: 0, l: 0, pf: 0, pa: 0, pts: 0 },
  { pos: 3, team: "Burlington RFC", p: 0, w: 0, d: 0, l: 0, pf: 0, pa: 0, pts: 0 },
  { pos: 4, team: "London RFC", p: 0, w: 0, d: 0, l: 0, pf: 0, pa: 0, pts: 0 },
  { pos: 5, team: "Brantford RFC", p: 0, w: 0, d: 0, l: 0, pf: 0, pa: 0, pts: 0 },
  { pos: 6, team: "Sarnia RFC", p: 0, w: 0, d: 0, l: 0, pf: 0, pa: 0, pts: 0 },
  { pos: 7, team: "Fergus RFC", p: 0, w: 0, d: 0, l: 0, pf: 0, pa: 0, pts: 0 },
  { pos: 8, team: "Stratford RFC", p: 0, w: 0, d: 0, l: 0, pf: 0, pa: 0, pts: 0 },
];

// ─── NEWS ARTICLES ────────────────────────────────────────────────────────────
export const articles = [
  {
    slug: "explanation-of-2026-junior-minor-fees",
    title: "Explanation of 2026 Junior & Minor Fees",
    excerpt: "A full breakdown of all registration fees for the 2026 season across every age group, from U6 Flag through to U18 contact rugby.",
    image: "https://images.pexels.com/photos/13583557/pexels-photo-13583557.jpeg?auto=compress&cs=tinysrgb&w=800",
    body: `Trevor Williams, Director of Junior Rugby, has published a detailed breakdown of all registration fees for the 2026 season. Here is a full explanation of what each age group pays and where those funds go.\n\nAll fees are set through a combination of Rugby Canada, Rugby Ontario, SWORU (Southwest Ontario Rugby Union), and Waterloo County club-level fees. The club has no control over the regulatory fees charged by Rugby Canada and Rugby Ontario, but works hard to keep club-level costs as low as possible while still providing a high-quality programme.\n\n**U6, U8 & U10 (Non-Contact Flag) — $292.00**\nRugby Canada insurance: $30.00 | Rugby Ontario admin: $32.54 | SWORU High-Performance: $5.00 | Club fees: $224.00. Club fees cover a Gilbert Canada kit, field maintenance, athletic therapy coverage at all contact sessions, and coach reimbursements for volunteer time.\n\n**U12 Boys & U12 Girls (Contact) — $347.54**\nRugby Canada: $40.00 | Rugby Ontario: $32.54 | SWORU: $5.00 | Club fees: $270.00.\n\n**U14 Boys & U14 Girls (Contact) — $427.00**\nRugby Canada: $82.50 | Rugby Ontario: $59.37 | SWORU: $5.00 | Club fees: $280.00. Note: U14 is a combined programme with Guelph RFC this season due to enrollment numbers.\n\n**U16 Boys & U16 Girls (Contact) — $470.00**\nRugby Canada: $116.05 | Rugby Ontario: $59.37 | SWORU: $5.00 | Club fees: $290.00.\n\n**U18 Boys & U18 Girls (Contact) — $470.00**\nIdentical breakdown to U16.\n\nRegistration for the 2026 season is now open through the PlayHQ platform. Please visit the club website for the direct registration link.`,
    category: "Announcements",
    date: "2026-03-02",
    author: "Trevor Williams",
    readTime: 3,
    tags: ["Registration", "2026 Season", "Junior Rugby", "Fees"],
  },
  {
    slug: "design-the-2026-training-tee",
    title: "Do You Want to Design the 2026 Waterloo County Training Tee?",
    excerpt: "Junior players and members are invited to submit a design for the official 2026 Waterloo County training tee. Submissions close April 3rd.",
    body: `The club is launching an exciting design competition for the 2026 junior training apparel — and we want YOU to create it!\n\nWaterloo County RFC is calling on all junior players, parents, and members to submit their sublimated tee designs by Friday, April 3rd, 2026. Submissions will be posted on our Instagram page (@waterloocountyrugby) for community voting, with the winning design announced on April 17th.\n\nAll junior kits include rugby shorts and a training tee, already covered in your 2026 registration fees. The club will not maintain inventory — instead, bulk orders will be placed on three dates:\n\n• May 1st order → estimated June 19th delivery\n• June 12th order → estimated July 31st delivery\n• June 26th order → estimated August 19th delivery\n\nOrders require minimum quantities through the supplier, so the earlier you register, the sooner your kit arrives!\n\nFor design submission guidelines or questions, please contact Trevor Williams, Director of Junior Rugby. Get creative — your design could be worn by every junior player in 2026!`,
    category: "Club News",
    date: "2026-03-01",
    author: "Trevor Williams",
    image: "https://images.pexels.com/photos/5116575/pexels-photo-5116575.jpeg?auto=compress&cs=tinysrgb&w=800",
    readTime: 2,
    tags: ["Junior Rugby", "2026 Season", "Kit", "Design Contest"],
  },
  {
    slug: "path-to-higher-competition-for-junior-athletes",
    title: "The Path to Higher Competition for Junior Athletes",
    excerpt: "Director of Junior Rugby Trevor Williams outlines the complete Rugby Ontario progression pathway — from club level all the way to national selection.",
    body: `Do you want to push yourself harder? Do you love playing rugby with and against the best players out there? If so, there is a clear pathway for junior athletes at Waterloo County RFC to reach higher levels of competition.\n\n**Club Level**\nOur club now features Regional Leagues (development-focused) and Cup Leagues (competitive select teams) at U16 and U18 divisions. Every player starts here.\n\n**SWORU (Southwest Ontario Rugby Union)**\nWaterloo County competes within SWORU, which organises regional competitions including U17 15s, U19 15s, U16 7s, and U18 7s. The top athletes from SWORU advance to provincial selection processes.\n\n**Ontario Blues Development Academy**\nThe Academy provides high-performance winter training from December through April, based at the University of Guelph. This is the proving ground for the province's best junior talent.\n\n**Provincial Level**\nTeam Ontario competes in the Canada Summer Games and Canadian Rugby Championships. Selection is based on performance at the Academy and SWORU levels.\n\n**National Rugby**\nThe highest tier — accessible through training camps and Rugby Canada selection. Players who have come through Waterloo County have gone on to represent Ontario and Canada.\n\nIf your goal is playing higher level rugby, Waterloo County will help you get there. Talk to Trevor Williams, Director of Junior Rugby, to find out more.\n\n— Trevor Williams, Director of Junior Rugby, Waterloo County RFC & High Performance Director, SWORU`,
    category: "Junior Rugby",
    date: "2025-03-02",
    author: "Trevor Williams",
    image: "https://images.pexels.com/photos/20399906/pexels-photo-20399906.jpeg?auto=compress&cs=tinysrgb&w=800",
    readTime: 4,
    tags: ["Junior Rugby", "Development", "SWORU", "Rugby Ontario", "High Performance"],
  },
  {
    slug: "u16-boys-2025-provincial-champions",
    title: "U16 Boys Win the 2025 Rugby Ontario Provincial Championship!",
    excerpt: "Our County U16 Boys defeated Guelph RFC in a thrilling championship final on July 26th, 2025 to claim the Rugby Ontario U16 Provincial title.",
    body: `Waterloo County RFC is absolutely delighted to announce that our County U16 Boys team are the 2025 Rugby Ontario U16 Provincial Champions!\n\nIn a thrilling final on July 26th, 2025, the boys faced local rivals Guelph RFC in what turned out to be a match of enormous pride and passion. Over 141 photos were captured from the day by club photographer Catey Fischer — a testament to just how special and memorable an occasion it was for everyone involved.\n\nThe championship win caps a remarkable summer season for the U16 programme, which saw the team compete in a packed schedule of SWORU league fixtures against Brantford, London, Guelph, Stratford, Sarnia, Middlesex, Middlesex/Sarnia, and Peterborough/Barrhaven.\n\nHighlights of the championship victory were featured on CBC Sports via their Pixellot platform, giving the players well-deserved province-wide recognition.\n\nThe club would like to thank all parents, coaches, volunteers, and supporters who made this season possible. A special mention to team photographer Catey Fischer for documenting every step of the journey.\n\nRegistration for the 2026 season is now open — come and be part of what promises to be another outstanding year for Waterloo County junior rugby!`,
    category: "Match Report",
    date: "2025-07-27",
    author: "Club Communications",
    image: "https://images.pexels.com/photos/35102692/pexels-photo-35102692.jpeg?auto=compress&cs=tinysrgb&w=800",
    readTime: 3,
    tags: ["U16 Boys", "Championship", "Rugby Ontario", "2025 Season", "Match Report"],
  },
  {
    slug: "2026-registration-now-open",
    title: "2026 Season Registration Now Open — Here's Everything You Need to Know",
    excerpt: "Registration for all 2026 Waterloo County RFC teams is now live through PlayHQ. Read the full details before registering.",
    body: `Registration for the 2026 Waterloo County RFC season is now officially open for all age groups, from County U8 Flag right through to Senior Men and Women.\n\nBefore registering, please read the following important points carefully:\n\n**How to Register**\nAll registration and payment is processed through the PlayHQ platform. Click the County Registration and Payment Link on the club website homepage or visit: playhq.com/ca/rugby-canada/register/21b765\n\n**Every member must re-register each season** — returning players are not automatically rolled over from previous years.\n\n**Fees for 2026**\nFee breakdowns are published in our separate "Explanation of 2026 Junior & Minor Fees" article. In summary:\n• U6 / U8 / U10 Flag: $292.00\n• U12 Contact: $347.54\n• U14 Contact: $427.00 (combined with Guelph)\n• U16 Contact: $470.00\n• U18 Contact: $470.00\n\nSenior fees will be communicated separately through the club.\n\n**Kit Orders**\nJunior kits (rugby shorts + training tee) are included in registration fees. Bulk kit orders are placed on May 1st, June 12th, and June 26th — register early for the earliest delivery!\n\nFor any questions, contact the club through the website or email directly. We look forward to welcoming everyone back for another fantastic season!`,
    category: "Announcements",
    date: "2026-02-28",
    author: "Club Communications",
    image: "https://images.pexels.com/photos/9799196/pexels-photo-9799196.jpeg?auto=compress&cs=tinysrgb&w=800",
    readTime: 3,
    tags: ["Registration", "2026 Season", "All Teams"],
  },
  {
    slug: "u18-season-review-2025",
    title: "U18 Season Review: A Year of Growth and Grit",
    excerpt: "A look back at the County U18 side's 2025 campaign — including a memorable 29–24 home win over London RFC and continued development under Trevor Williams.",
    body: `As the 2025 season draws to a close, Trevor Williams takes a look back at what the County U18 programme achieved — and where the team is headed for 2026.\n\nThe U18 side produced some memorable performances throughout the summer, none more so than the hard-fought 29–24 home victory over London RFC. That result demonstrated the quality and character within the squad, and gave the players a platform to grow from.\n\nThe campaign also included a difficult 5–29 defeat to a strong Fergus RFC side away from home — a result that provided valuable lessons about physicality and game management at the top end of junior rugby.\n\nPlayoff rugby provided further experience for the squad, with a trip to Sarnia representing a tough test against quality SWORU opposition.\n\nLooking ahead to 2026, Trevor Williams notes that several U18 players have shown the potential to access higher levels of competition through SWORU's U17 and U19 provincial programmes, as well as the Ontario Blues Development Academy.\n\nRegistration for U18 in 2026 is now open at $470.00. All enquiries about the junior programme should be directed to Trevor Williams, Director of Junior Rugby.`,
    category: "Club News",
    date: "2025-08-20",
    author: "Trevor Williams",
    image: "https://images.pexels.com/photos/29715715/pexels-photo-29715715.jpeg?auto=compress&cs=tinysrgb&w=800",
    readTime: 3,
    tags: ["U18", "Season Review", "2025", "Junior Rugby"],
  },
];

// ─── SPONSORS ─────────────────────────────────────────────────────────────────
export const sponsors = {
  title: [
    {
      name: "Josslin Insurance",
      logo: "https://placehold.co/400x200/1A2744/D4AF37?text=Josslin+Insurance",
      description: "Proud Senior Men's Sponsor of Waterloo County RFC. Josslin Insurance has been serving the Waterloo Region with comprehensive personal and business insurance solutions for over 60 years.",
      website: "https://www.josslin.com/",
      tier: "title",
    },
  ],
  gold: [
    {
      name: "Personal Edge Training",
      logo: "https://placehold.co/300x120/1A2744/D4AF37?text=Personal+Edge+Training",
      description: "Official Ball Sponsor of Waterloo County RFC.",
      website: "https://www.personaledgetraining.com/",
      tier: "gold",
    },
    {
      name: "Wood-Hall Logistics",
      logo: "https://placehold.co/300x120/1A2744/D4AF37?text=Wood-Hall+Logistics",
      description: "Club Sponsor of Waterloo County RFC.",
      website: "https://wood-hall.com/",
      tier: "gold",
    },
  ],
  silver: [
    {
      name: "Fall's Road Pub",
      logo: "https://placehold.co/240x100/1A2744/D4AF37?text=Fall%27s+Road+Pub",
      description: "Official Socials Sponsor of Waterloo County RFC.",
      website: "http://thefallsroadpub.ca/",
      tier: "silver",
    },
    {
      name: "Impact Canopy",
      logo: "https://placehold.co/240x100/1A2744/D4AF37?text=Impact+Canopy",
      description: "Official Tent Sponsor of Waterloo County RFC.",
      website: "https://impactcanopy.ca/",
      tier: "silver",
    },
    {
      name: "Kidspired",
      logo: "https://placehold.co/240x100/1A2744/D4AF37?text=Kidspired",
      description: "Sponsorship Partner of Waterloo County RFC.",
      website: "https://www.kidspired.ca/",
      tier: "silver",
    },
  ],
  bronze: [
    {
      name: "Barbarian Rugby",
      logo: "https://placehold.co/180x80/F8F6F0/1A2744?text=Barbarian",
      website: "https://barbarian.com/",
      tier: "bronze",
    },
    {
      name: "Domino's",
      logo: "https://placehold.co/180x80/F8F6F0/1A2744?text=Domino%27s",
      website: "https://www.dominos.ca/",
      tier: "bronze",
    },
    {
      name: "City of Waterloo",
      logo: "https://placehold.co/180x80/F8F6F0/1A2744?text=City+of+Waterloo",
      website: "http://www.waterloo.ca/",
      tier: "bronze",
    },
    {
      name: "City of Kitchener",
      logo: "https://placehold.co/180x80/F8F6F0/1A2744?text=City+of+Kitchener",
      website: "http://www.kitchener.ca/",
      tier: "bronze",
    },
  ],
};

// ─── GALLERY ──────────────────────────────────────────────────────────────────
// Real photo albums from the 2025 season
export const galleryImages = [
  {
    id: 1,
    src: "https://images.pexels.com/photos/8530366/pexels-photo-8530366.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "County U16 Boys — 2025 Rugby Ontario Provincial Championship vs Guelph RFC (July 26, 2025)",
    category: "Matches",
    date: "2025-07-26",
    album: "Championship Game vs Guelph — July 26, 2025 (141 photos by Catey Fischer)",
  },
  {
    id: 2,
    src: "https://images.pexels.com/photos/3624737/pexels-photo-3624737.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Boys vs Middlesex / Sarnia — SWORU League (July 26, 2025)",
    category: "Matches",
    date: "2025-07-26",
    album: "July 26 vs Guelph Part 2 (88 photos)",
  },
  {
    id: 3,
    src: "https://images.pexels.com/photos/35102692/pexels-photo-35102692.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Boys vs Peterborough / Barrhaven (Aug 10, 2025)",
    category: "Matches",
    date: "2025-08-10",
    album: "2025.08.10 — U16 vs Peterborough/Barrhaven (60 photos)",
  },
  {
    id: 4,
    src: "https://images.pexels.com/photos/31003857/pexels-photo-31003857.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Parents BBQ — Club social event",
    category: "Events",
    date: "2025-07-01",
    album: "U16 Parents BBQ (61 photos by Anelle Steyn)",
  },
  {
    id: 5,
    src: "https://images.unsplash.com/photo-1613332331877-8a47030be80b?w=800&q=80",
    alt: "County U6 and U8 mini rugby players — 2024 season",
    category: "Club Life",
    date: "2024-07-01",
    album: "2024 — U6 and U8 Photos (16 photos by Jessie Brush)",
  },
  {
    id: 6,
    src: "https://images.pexels.com/photos/3641367/pexels-photo-3641367.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Boys vs Brantford RFC — SWORU League (July 19, 2025)",
    category: "Matches",
    date: "2025-07-19",
    album: "2025.07.19 — U16 vs Brantford (36 photos)",
  },
  {
    id: 7,
    src: "https://images.pexels.com/photos/20192747/pexels-photo-20192747.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Boys vs London / Guelph — SWORU League (July 19, 2025)",
    category: "Matches",
    date: "2025-07-19",
    album: "2025.07.19 — U16 vs London/Guelph (45 photos)",
  },
  {
    id: 8,
    src: "https://images.pexels.com/photos/9799211/pexels-photo-9799211.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Boys vs Guelph RFC (July 26, 2025) — Part 3",
    category: "Matches",
    date: "2025-07-26",
    album: "July 26th vs Guelph Part 3 (47 photos by Catey Fischer)",
  },
  {
    id: 9,
    src: "https://images.pexels.com/photos/8592966/pexels-photo-8592966.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Boys vs Brantford RFC — SWORU League (July 12, 2025)",
    category: "Matches",
    date: "2025-07-12",
    album: "2025.07.12 — U16 vs Brantford (44 photos)",
  },
  {
    id: 10,
    src: "https://images.pexels.com/photos/20399906/pexels-photo-20399906.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Boys vs Stratford / Sarnia — SWORU League (July 12, 2025)",
    category: "Matches",
    date: "2025-07-12",
    album: "2025.07.12 — U16 vs Stratford/Sarnia (48 photos)",
  },
  {
    id: 11,
    src: "https://images.pexels.com/photos/9799193/pexels-photo-9799193.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Boys vs Guelph RFC (July 10, 2025)",
    category: "Matches",
    date: "2025-07-10",
    album: "2025.07.10 — U16 vs Guelph (20 photos)",
  },
  {
    id: 12,
    src: "https://images.pexels.com/photos/29292737/pexels-photo-29292737.jpeg?auto=compress&cs=tinysrgb&w=800",
    alt: "U16 Boys vs London / Sarnia / Fergus — SWORU (July 5, 2025)",
    category: "Matches",
    date: "2025-07-05",
    album: "2025.07.05 — U16 vs London/Sarnia/Fergus (101 photos)",
  },
];

// ─── CLUB STATS ───────────────────────────────────────────────────────────────
export const clubStats = [
  { label: "Affiliations", value: "2", icon: "Shield" },
  { label: "Teams", value: "12", icon: "Users" },
  { label: "Age Groups", value: "U6–Sen", icon: "Calendar" },
  { label: "Champions", value: "2025", icon: "Trophy" },
];

// ─── MEMBERSHIP TIERS ─────────────────────────────────────────────────────────
export const membershipTiers = [
  {
    id: "u6-u10-flag",
    name: "Mini Flag",
    subtitle: "U6, U8 & U10",
    price: 292,
    currency: "CAD",
    perks: [
      "Non-contact flag rugby",
      "Gilbert Canada kit included",
      "Field & equipment access",
      "Athletic therapy coverage",
      "Family Day event",
      "Rugby Canada insurance",
      "Rugby Ontario registration",
    ],
    recommended: false,
    cta: "Register Minis",
  },
  {
    id: "u12-contact",
    name: "U12 Contact",
    subtitle: "Under 12",
    price: 348,
    currency: "CAD",
    perks: [
      "Full contact rugby programme",
      "Gilbert Canada kit included",
      "SWORU competition access",
      "Certified coaching",
      "Athletic therapy at all sessions",
      "Rugby Canada insurance",
      "Rugby Ontario registration",
    ],
    recommended: false,
    cta: "Register U12",
  },
  {
    id: "u14-u16-contact",
    name: "Junior Contact",
    subtitle: "U14 & U16",
    price: 470,
    currency: "CAD",
    perks: [
      "Full contact rugby",
      "SWORU league & cup competitions",
      "Provincial development pathway",
      "Coaching by certified staff",
      "Athletic therapy coverage",
      "Access to Ontario Blues pathway",
      "Rugby Canada & Ontario registration",
    ],
    recommended: true,
    cta: "Register Junior",
  },
  {
    id: "u18-senior",
    name: "U18 & Senior",
    subtitle: "U18 + Adult",
    price: 470,
    currency: "CAD",
    perks: [
      "Full contact rugby — all divisions",
      "SWORU U18 & Senior leagues",
      "Provincial & national pathways",
      "High-performance development",
      "Mixed Ability / Social option",
      "Full insurance coverage",
      "Rugby Canada & Ontario registration",
    ],
    recommended: false,
    cta: "Register Senior",
  },
];

// ─── TESTIMONIALS ─────────────────────────────────────────────────────────────
export const testimonials = [
  {
    name: "U16 Parent",
    role: "Parent of U16 Player",
    years: "With the club since 2023",
    quote: "Watching the U16 boys win the 2025 Rugby Ontario Provincial Championship was one of the proudest moments of our family's sporting life. The coaches and the whole club family made it possible.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  },
  {
    name: "Senior Men's Player",
    role: "County Senior Men",
    years: "Member for 4 years",
    quote: "I moved to Waterloo for work and joined the club knowing nobody. Within weeks I had a community. The rugby is competitive, the people are brilliant — I wouldn't change it for anything.",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
  },
  {
    name: "Junior Parent & Volunteer",
    role: "U8 Flag Parent",
    years: "Member since 2024",
    quote: "The U8 flag programme is outstanding. The coaches make it so fun — my daughter absolutely loves Saturday mornings at Waterloo County. The kit is a bonus that she wears everywhere!",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
  },
];

// ─── COMMITTEE MEMBERS ────────────────────────────────────────────────────────
export const committee = [
  {
    name: "Josh Windsor",
    role: "Club President",
    email: "president@waterloocountyrugby.com",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&q=80",
  },
  {
    name: "Stu Bailey",
    role: "Club Secretary",
    email: "secretary@waterloocountyrugby.com",
    image: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=300&q=80",
  },
  {
    name: "Eric Ciezar",
    role: "Director of Operations & Finance",
    email: "finance@waterloocountyrugby.com",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&q=80",
  },
  {
    name: "Trevor Williams",
    role: "Director of Junior Rugby",
    email: "juniors@waterloocountyrugby.com",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&q=80",
  },
];

// ─── TIMELINE ─────────────────────────────────────────────────────────────────
export const timeline = [
  {
    year: "Founded",
    milestone: "Waterloo County Rugby Club Established",
    description: "Waterloo County RFC is founded, joining Rugby Ontario and Rugby Canada as the primary rugby club serving the Waterloo Region.",
  },
  {
    year: "Early Years",
    milestone: "Club Grows Across All Ages",
    description: "The club expands beyond senior men's rugby to include junior and women's sections, reflecting the community's passion for the sport across all age groups.",
  },
  {
    year: "2018",
    milestone: "Rugby Ontario U16 Championship Win",
    description: "A historic U16 provincial championship for the club, captured in highlights aired on CBC Sports and cementing Waterloo County's reputation as a junior powerhouse.",
  },
  {
    year: "2024",
    milestone: "Expanded Junior Programme",
    description: "The club launches the U6 and U8 Flag rugby programme, welcoming the youngest members of the Waterloo community to the sport with non-contact tag rugby.",
  },
  {
    year: "2025",
    milestone: "U16 Boys — Rugby Ontario Provincial Champions",
    description: "The County U16 Boys defeat Guelph RFC in the Rugby Ontario U16 Provincial Championship final on July 26th — one of the club's proudest moments.",
  },
  {
    year: "2026",
    milestone: "12 Teams, Record Registration Drive",
    description: "Waterloo County RFC fields 12 teams from U8 Flag through to Senior Men and Women, with 2026 registration open across all age groups via PlayHQ.",
  },
];
